import type { Metadata } from 'next'
import { env } from '@/lib/env'
import { siteConfig } from '@/lib/config'
import { CONTACT_INFO } from '@/features/content/data/contact'
import type { FaqGroup } from '@/features/content/types'
import type { CatalogCurrency, Product } from '@/types/catalog'

/** Canonical site origin, no trailing slash. `NEXT_PUBLIC_SITE_URL` in prod; localhost in dev. */
// `env.ts`'s Zod schema owns validation and the localhost default; this only normalises a trailing slash so every SITE_URL consumer can safely concatenate paths.
export const SITE_URL: string = env.NEXT_PUBLIC_SITE_URL.replace(/\/+$/, '')

/** `absoluteUrl('/products/x')` → `${SITE_URL}/products/x`; passes through absolute inputs unchanged. */
export function absoluteUrl(path: string): string {
  if (/^https?:\/\//i.test(path)) return path
  const normalizedPath = path.startsWith('/') ? path : `/${path}`
  return `${SITE_URL}${normalizedPath}`
}

/**
 * Sitewide social card, generated by `scripts/generate-brand-assets.ts`.
 * 1200x630, the size every major platform crops from.
 */
export const DEFAULT_OG_IMAGE = '/og-default.png'

/** Square brand mark, same generator. Raster because schema.org `logo` rejects SVG. */
export const LOGO_IMAGE = '/logo.png'

/**
 * Shared `openGraph`/`twitter` builder for per-page metadata. A page that
 * sets `openGraph` REPLACES the layout's object wholesale (Next does not
 * merge those per-field), so this builder restates `siteName` itself — do
 * not delete that line expecting the layout's value to survive. Pages that
 * call this therefore ship their own title/description AND `og:site_name`;
 * pages that set no `openGraph` at all inherit the layout's
 * `{ type, siteName }` and let Next backfill their own copy into `og:*`.
 *
 * That wholesale-replacement rule is also why `image` falls back to
 * `DEFAULT_OG_IMAGE` rather than being omitted when absent: a caller with no
 * image of its own would otherwise replace the layout's object with one
 * carrying no `images` at all, and unfurl with a blank card — strictly worse
 * than the page having set nothing. An image-less product is a real case (the
 * relation is 0..n), so this is the path that runs, not a theoretical one.
 */
export function pageCards({
  title,
  description,
  path,
  image,
}: {
  title: string
  description: string
  path: string
  image?: string
}): Pick<Metadata, 'openGraph' | 'twitter'> {
  const absoluteImage = absoluteUrl(image ?? DEFAULT_OG_IMAGE)

  return {
    openGraph: {
      type: 'website',
      siteName: siteConfig.name,
      title,
      description,
      url: absoluteUrl(path),
      images: [absoluteImage],
    },
    twitter: {
      card: 'summary_large_image',
      title,
      description,
      images: [absoluteImage],
    },
  }
}

/** Minor units → JSON-LD decimal string, e.g. 4_500_000 → '45000.00'. Derived from integer minor units, never floats. */
export function priceString(amountMinor: number): string {
  return (amountMinor / 100).toFixed(2)
}

const CURRENCY_KEY: Record<CatalogCurrency, 'ngn' | 'usd'> = { NGN: 'ngn', USD: 'usd' }

/**
 * Sitewide publisher identity. `logo` is what Google reads for the SERP/
 * knowledge-panel mark, and it must be a raster URL — SVG is not an accepted
 * format for this property, which is why the generator emits `logo.png`.
 *
 * `contactPoint` uses the published support mailbox rather than a phone
 * number: email is the channel the returns policy actually directs customers
 * to, and claiming a support line the business does not staff would be worse
 * than omitting one.
 */
export function organizationJsonLd(): Record<string, unknown> {
  return {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: siteConfig.name,
    description: siteConfig.description,
    url: SITE_URL,
    logo: absoluteUrl(LOGO_IMAGE),
    image: absoluteUrl(DEFAULT_OG_IMAGE),
    address: {
      '@type': 'PostalAddress',
      addressLocality: 'Lagos',
      addressCountry: 'NG',
    },
    contactPoint: {
      '@type': 'ContactPoint',
      contactType: 'customer support',
      email: CONTACT_INFO.email,
      areaServed: 'Worldwide',
      availableLanguage: 'English',
    },
    sameAs: [siteConfig.social.instagram],
  }
}

/**
 * `WebSite` + `SearchAction`, which is what makes Google eligible to render a
 * sitelinks searchbox against the domain. The target must match the real
 * query contract of `/search` — `parseSearchCriteria` reads `q`, so that is
 * the parameter named here; pointing it at anything else would produce a
 * searchbox that silently returns the unfiltered catalog.
 */
export function webSiteJsonLd(): Record<string, unknown> {
  return {
    '@context': 'https://schema.org',
    '@type': 'WebSite',
    name: siteConfig.name,
    url: SITE_URL,
    potentialAction: {
      '@type': 'SearchAction',
      target: {
        '@type': 'EntryPoint',
        urlTemplate: absoluteUrl('/search?q={search_term_string}'),
      },
      'query-input': 'required name=search_term_string',
    },
  }
}

/**
 * `FAQPage` from the same `FAQ_GROUPS` the page renders, flattened across
 * headings — schema.org has no notion of grouped questions, and the grouping
 * is presentational. Built from the rendered source so the two can never drift:
 * markup describing answers a visitor cannot find on the page is a structured-
 * data violation, not just a mismatch.
 */
export function faqJsonLd(groups: readonly FaqGroup[]): Record<string, unknown> {
  return {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: groups.flatMap((group) =>
      group.items.map((item) => ({
        '@type': 'Question',
        name: item.q,
        acceptedAnswer: { '@type': 'Answer', text: item.a },
      })),
    ),
  }
}

/** Days a generated `priceValidUntil` sits in the future. See `productJsonLd`. */
const PRICE_VALIDITY_DAYS = 365

/**
 * Return terms, transcribed from the published Shipping & Returns policy
 * (`features/content/data/policies.ts`). Every value here is a promise the
 * business has already made in prose — this is markup of that policy, never a
 * new commitment. If the policy copy changes, these change with it.
 *
 * `merchantReturnDays` takes the OUTER bound of the published "2–3 days"
 * window: the schema field is a single number, and understating it would deny
 * a return the policy text grants.
 */
const RETURN_POLICY = {
  '@type': 'MerchantReturnPolicy',
  applicableCountry: 'NG',
  returnPolicyCategory: 'https://schema.org/MerchantReturnFiniteReturnWindow',
  merchantReturnDays: 3,
  returnMethod: 'https://schema.org/ReturnByMail',
  // The policy puts return postage on the customer except for damaged or
  // faulty goods.
  returnFees: 'https://schema.org/ReturnShippingFees',
} as const

/**
 * Delivery expectations for Nigerian addresses, from the same policy source.
 * Handling is the published 5–8 day make time (personalised pieces run to
 * 2–3 weeks and are deliberately not represented by this single range);
 * transit spans Lagos's 2–5 days through 5–10 days elsewhere in the country.
 *
 * `shippingRate` is DELIBERATELY ABSENT. Nigerian shipping is quoted live per
 * address and order weight at checkout, so there is no single figure that is
 * true — publishing one would be a price claim the checkout then contradicts.
 * Schema.org permits `deliveryTime` without a rate; an accurate partial record
 * beats a complete but false one.
 */
const SHIPPING_DETAILS = {
  '@type': 'OfferShippingDetails',
  shippingDestination: { '@type': 'DefinedRegion', addressCountry: 'NG' },
  deliveryTime: {
    '@type': 'ShippingDeliveryTime',
    handlingTime: { '@type': 'QuantitativeValue', minValue: 5, maxValue: 8, unitCode: 'DAY' },
    transitTime: { '@type': 'QuantitativeValue', minValue: 2, maxValue: 10, unitCode: 'DAY' },
  },
} as const

/**
 * `now` is injected rather than read inside so the output stays deterministic
 * under test. In production it is the generation timestamp: this route is ISR
 * (hourly), so `priceValidUntil` simply rolls forward on each regeneration,
 * which is the intended behaviour for a catalog whose prices do not expire.
 * Google warns on offers missing the field, so omitting it is not an option.
 *
 * No `aggregateRating`/`review` is emitted, and that omission is deliberate:
 * there is no product review system, and review markup without reviews behind
 * it is grounds for a manual action. The home page testimonials are
 * brand-level and do not map to individual products.
 */
export function productJsonLd(
  product: Product,
  currency: CatalogCurrency,
  now: Date = new Date(),
): Record<string, unknown> {
  const key = CURRENCY_KEY[currency]
  const priceSet = product.salePriceSet ?? product.priceSet
  // A variant product's own `inventory` column is unused (schema tracks
  // per-variant inventory instead), so availability must also check variants.
  const inStock = product.inventory > 0 || product.variants.some((variant) => variant.inventory > 0)

  const validUntil = new Date(now)
  validUntil.setUTCDate(validUntil.getUTCDate() + PRICE_VALIDITY_DAYS)

  return {
    '@context': 'https://schema.org',
    '@type': 'Product',
    name: product.name,
    description: product.shortDescription,
    sku: product.sku,
    // Omit `image` entirely for an image-less product rather than emitting
    // `image: []` — Google's structured-data validator treats an empty array
    // as a present-but-invalid value, not as "field absent".
    ...(product.images.length > 0 ? { image: product.images.map((image) => absoluteUrl(image.src)) } : {}),
    brand: { '@type': 'Brand', name: siteConfig.name },
    offers: {
      '@type': 'Offer',
      price: priceString(priceSet[key].amountMinor),
      priceCurrency: currency,
      priceValidUntil: validUntil.toISOString().slice(0, 10),
      // Everything is made new in the Lagos workshop; there is no resale or
      // refurbished inventory.
      itemCondition: 'https://schema.org/NewCondition',
      availability: inStock ? 'https://schema.org/InStock' : 'https://schema.org/OutOfStock',
      url: absoluteUrl(`/products/${product.slug}`),
      seller: { '@type': 'Organization', name: siteConfig.name },
      hasMerchantReturnPolicy: RETURN_POLICY,
      shippingDetails: SHIPPING_DETAILS,
    },
  }
}

export function breadcrumbJsonLd(trail: Array<{ name: string; path: string }>): Record<string, unknown> {
  return {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: trail.map((crumb, index) => ({
      '@type': 'ListItem',
      position: index + 1,
      name: crumb.name,
      item: absoluteUrl(crumb.path),
    })),
  }
}
